
version: 0.2
phases:
  pre_build:
    commands:
    - echo "Entered the pre-build phase"
  build:
    commands:
    - echo "Entered build phase"
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - mvn package
artifacts:
  files:
    - imagedefinitions.json
    - target/notification-service.jar
  discard-paths: yes